version: 1
default_environment: userdev
send_anonymous_usage_stats: true
project_id: c15e971a-d318-4a9d-979b-1039ce5fd1b1
include_paths:
- ./environments/*.meltano.yml
- ./extract/*.meltano.yml
- ./load/*.meltano.yml
- ./orchestrate/*.meltano.yml
- ./transform/*.meltano.yml
- ./utilities/*.meltano.yml
plugins:
  transformers:
  - name: dbt-postgres
    variant: dbt-labs
    pip_url: dbt-core~=1.0.0 dbt-postgres~=1.0.0
schedules:
- name: daily-postgres-load
  interval: '@daily'
  job: tap-postgres-to-target-postgres
jobs:
- name: tap-postgres-to-target-postgres
  tasks:
  - tap-postgres target-postgres
